---

# Ansible playbooy used to deploy three Web servers (two on a CentOS Docker
# container, another one on a Ubuntu 14.04.3 Docker container).
# Then, deploy keepalived to manage a shared VIP and then HAproxy used to
# load-balance (and health-check) these three Web servers.

- name: Deploy Web servers
  hosts: webservers
  become: true
  roles:
  - webserver

- name: Configure load-balancing
  hosts: loadbalancers
  become: true
  vars_files:
  - vars/main.yml
  roles:
   - keepalived
   - haproxy

- name: Final checks
  hosts: localhost
  gather_facts: false
  vars_files:
  - vars/main.yml
  tasks:
  - name: Wait for keepalived to settle down
    local_action:
      module: wait_for
      port: 22
      host: "{{keepalived_shared_ip}}"
      search_regex: OpenSSH
      delay: 10
